CREATE TABLE IF NOT EXISTS mail_items (
    message_key TEXT PRIMARY KEY,
    subject TEXT NOT NULL,
    sender TEXT,
    sender_domain TEXT,
    source_folder_name TEXT,
    source_folder_path TEXT,
    source_store_name TEXT,
    received_utc TEXT,
    body_preview TEXT,
    body_path TEXT,
    source_path TEXT,
    raw_message_path TEXT,
    attachment_count INTEGER NOT NULL DEFAULT 0,
    has_attachments INTEGER NOT NULL DEFAULT 0,
    analyzed_attachment_count INTEGER NOT NULL DEFAULT 0,
    attachment_summary TEXT,
    attachment_kinds_json TEXT NOT NULL DEFAULT '[]',
    attachment_analysis_path TEXT,
    attachment_analysis_json TEXT NOT NULL DEFAULT '[]',
    process_type TEXT NOT NULL,
    confidence REAL NOT NULL,
    needs_action INTEGER NOT NULL DEFAULT 0,
    urgency TEXT NOT NULL,
    labels_json TEXT NOT NULL,
    decision_mode TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    decision_reason TEXT NOT NULL,
    status TEXT NOT NULL,
    service_level_state TEXT NOT NULL,
    owner TEXT,
    queue_name TEXT,
    web_link TEXT,
    created_utc TEXT NOT NULL,
    updated_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mail_audit_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_key TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_utc TEXT NOT NULL
);
